/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pokemon;

import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;

/**
 *
 * @author LEONARDOESLABAOBARBO
 */
public class Tela extends javax.swing.JFrame {

    private Image imagemFundo;
    
    private ArrayList<Pokemon> pokemonsArrayList = new ArrayList<>();
    private ArrayList<Pokemon> mochilaArrayList = new ArrayList<>();

    private DefaultListModel<String> mochilaLista;
    private DefaultListModel<String> pokemonLista;

    public Tela() {
        
        initComponents();
       
        
        mochilaLista = new DefaultListModel<>();
        mochila.setModel(mochilaLista);

        pokemonLista = new DefaultListModel<>();
        pokemons.setModel(pokemonLista);

        pokemonsArrayList.add(new Pokemon("Datena", "Brasil Urgente", 3));
        pokemonsArrayList.add(new Pokemon("Rogerio", "O+", 60));
        pokemonsArrayList.add(new Pokemon("Matue", "Maconheiro", 10));
        pokemonsArrayList.add(new Pokemon("Alemao surfista", "surfista", 18));
        pokemonsArrayList.add(new Pokemon("Keller maniaco", "raro", 20));
        pokemonsArrayList.add(new Pokemon("Nepo Baby", "Xuxu", 8));
        pokemonsArrayList.add(new Pokemon("Davy Jones", "Easter Egg", 40));
        pokemonsArrayList.add(new Pokemon("Senac", "Estudantil", 1000));
        pokemonsArrayList.add(new Pokemon("Unisinos", "Decadente", 1));
        pokemonsArrayList.add(new Pokemon("Confuso sobrinho", "Confuso", 90));

        for (Pokemon pokemon : pokemonsArrayList) {
            String linhaFormatada = String.format("%-20s%-15s%-5d", pokemon.getNome(), pokemon.getTipo(), pokemon.getNivel());
            pokemonLista.addElement(linhaFormatada);
        }

        pokemons.setFont(new Font("Monospaced", Font.PLAIN, 14));
        mochila.setFont(new Font("Monospaced", Font.PLAIN, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        mochila = new javax.swing.JList<>();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pokemons = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        mochila.setBackground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setViewportView(mochila);

        jScrollPane2.setViewportView(jScrollPane1);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        pokemons.setBackground(new java.awt.Color(255, 255, 0));
        jScrollPane3.setViewportView(pokemons);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnRemover))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        if (mochilaLista.size() < 6) {
            int index = pokemons.getSelectedIndex();
            if (index != -1) { // Verifica se algo foi selecionado
                //mochilaLista.addElement(pokemonLista.get(index));
                mochilaArrayList.add(pokemonsArrayList.get(index));
                pokemonsArrayList.remove(index);
                atualizaListas();
            }
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void atualizaListas() {
        pokemonLista.clear();
        mochilaLista.clear();

        for (Pokemon pokemon : pokemonsArrayList) {
            String linhaFormatada = String.format("%-20s%-15s%-5d", pokemon.getNome(), pokemon.getTipo(), pokemon.getNivel());
            pokemonLista.addElement(linhaFormatada);
        }

        for (Pokemon pokemon : mochilaArrayList) {
            String linhaFormatada = String.format("%-20s%-15s%-5d", pokemon.getNome(), pokemon.getTipo(), pokemon.getNivel());
            mochilaLista.addElement(linhaFormatada);
        }
    }
    
    
    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

        int index = mochila.getSelectedIndex();
        if (index != -1) {
            pokemonsArrayList.add(mochilaArrayList.get(index));
            mochilaArrayList.remove(index);
            atualizaListas();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> mochila;
    private javax.swing.JList<String> pokemons;
    // End of variables declaration//GEN-END:variables
}
